### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by swoopae** [SinnerTF2/PlagueStealer#1]
now i finally have access to plaguecheat hvh.

(will be fixed next loader update)

**Comment by cristeigabriela** [comment]
blague cheat 👽

**Comment by SinnerK0N** [comment]
:trollface: thank you!!!!! :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:
